# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-01 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aferidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='DependenciaSetor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Dependencia de setor')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('estado', models.IntegerField(choices=[(-1, 'Nao encontrado'), (1, 'Bom'), (2, 'Ocioso'), (3, 'Danificado'), (4, 'Sem condicoes de uso')], default=-1, verbose_name='Estado do bem')),
                ('obs', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observacao')),
                ('aferidores', models.ManyToManyField(to='app.Aferidor')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('patrimonio', models.IntegerField(blank=True, null=True, verbose_name='Patrimonio antigo')),
                ('sipac', models.IntegerField(blank=True, null=True, verbose_name='Patrimonio novo')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.DependenciaSetor')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Setor')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Item'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.DependenciaSetor'),
        ),
        migrations.AddField(
            model_name='dependenciasetor',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Setor'),
        ),
    ]
