# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-04 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171201_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='setor',
            field=models.CharField(max_length=255, verbose_name='Setor encontrado'),
        ),
    ]
