# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-04 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171204_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='aferidores',
        ),
        migrations.AddField(
            model_name='inventario',
            name='aferidores',
            field=models.CharField(default='', max_length=255, verbose_name='Aferidor'),
            preserve_default=False,
        ),
    ]
