# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171204_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Item', to_field='sipac', unique=True),
        ),
    ]
