# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171204_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='setor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor encontrado'),
        ),
    ]
