# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171211_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloco',
            options={'verbose_name': 'Bloco', 'verbose_name_plural': 'Blocos'},
        ),
        migrations.AlterModelOptions(
            name='dependenciasetor',
            options={'verbose_name': 'Dependencia de setor', 'verbose_name_plural': 'Dependencias'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor Responsavel', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AddField(
            model_name='setor',
            name='nomeNovo',
            field=models.CharField(default='', max_length=255, verbose_name='Setor / NOME ATUAL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dependenciasetor',
            name='nomeNovo',
            field=models.CharField(max_length=255, verbose_name='Dependencia do Setor / NOME ATUAL'),
        ),
    ]
