# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20171211_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependenciasetor',
            name='nomeNovo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dependencia do Setor / NOME ATUAL'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nomeNovo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor / NOME ATUAL'),
        ),
    ]
