# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171211_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependenciasetor',
            name='nomeNovo',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='nomeNovo',
        ),
    ]
