# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20171211_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependenciaSetorNovo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Dependencia de setor / NOVO')),
            ],
            options={
                'verbose_name': 'Dependencia de setor',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='SetorNovo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Setor Responsavel / NOVO')),
                ('bloco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Bloco')),
            ],
            options={
                'verbose_name': 'Setor Responsavel',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.AddField(
            model_name='dependenciasetornovo',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.SetorNovo'),
        ),
        migrations.AlterUniqueTogether(
            name='dependenciasetornovo',
            unique_together=set([('nome', 'setor')]),
        ),
    ]
