# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20171211_1806'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependenciasetornovo',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dependenciasetornovo',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='setornovo',
            name='bloco',
        ),
        migrations.AddField(
            model_name='dependenciasetor',
            name='nomeNovo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dependencia do Setor / NOME ATUAL'),
        ),
        migrations.AddField(
            model_name='setor',
            name='nomeNovo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor / NOME ATUAL'),
        ),
        migrations.DeleteModel(
            name='DependenciaSetorNovo',
        ),
        migrations.DeleteModel(
            name='SetorNovo',
        ),
    ]
