# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20171211_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='bloco',
        ),
        migrations.AddField(
            model_name='dependenciasetor',
            name='bloco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Bloco'),
        ),
    ]
