# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20171211_1816'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependenciasetor',
            unique_together=set([('nomeNovo', 'setor')]),
        ),
    ]
