# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20171211_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterField(
            model_name='dependenciasetor',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dependencia de setor / NOME ANTIGO'),
        ),
        migrations.AlterField(
            model_name='dependenciasetor',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Setor'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor / NOME ANTIGO'),
        ),
    ]
