# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20171212_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.Item', to_field='sipac'),
        ),
    ]
