# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20171213_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='setorTmp',
        ),
    ]
